Setup Application Database and Tables with Tests
iTaylorCodes/Gamr pull request #13
Opened 2021-07-27 05:45 UTC by iTaylorCodes

### What does this PR do?
- This Pull Request sets up the application database and tables with tests for the models and methods.
- This PR closes #4 
### Description of Task to be completed
- Create the database and testing database using PostgreSQL. Setup User, Match, and Favorites, models using SQLAlchemy. Add class methods on User model for Signup and Authenticate. Add match methods to match 2 users together. Create tests for all models and methods.
### How should this be manually tested?
- First use "export FLASK_ENV=testing" to enter the testing environment. Then use "python -m unittest tests/test_user_model.py", "python -m unittest tests/test_match_model.py", or "python -m unittest tests/test_favorites_model.py"

2021-07-27 08:28 UTC, alexkayabula requested changes
@iTaylorCodes set up the **travis.yml** file to build and run tests from the **test database**.

2021-07-27 08:28 UTC, alexkayabula commented on config.py
> +    SQLALCHEMY_DATABASE_URI = 'postgresql:///gamr'
Add a parent configuration class from which these settings can be inherited by other configuration classes.

2021-07-27 08:33 UTC, alexkayabula commented
@iTaylorCodes change the title of this PR. Remove `with Tests`.

2021-07-27 21:25 UTC, iTaylorCodes commented
@alexkayabula Added PostgreSQL database to travis.yml. Tests are running through Travis CI now 👍

2021-07-28 01:47 UTC, alexkayabula approved these changes
LGTM

2021-07-28 01:47 UTC, merged